server:
  port: 8200
spring:
  graphql:
    path: /my-graphql
    playground:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/client_data
    username: root
    password: root

    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  level:
    root: info


