server:
  port: 8200
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/client_data
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
lm:
  api:
    playground:
      enabled: ${LM_API_PLAYGROUND_ENABLED:false}
    key: ${LM_API_KEY}
logging:
  level:
    root: info