server:
  port: 8200
  host: 0.0.0.0
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/client_data?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
lm:
  api:
    playground:
      enabled: ${LM_API_PLAYGROUND_ENABLED:false}
    key: ${LM_API_KEY:key01}
logging:
  level:
    root: info
